server:
  port: 8088
  contextPath: /boot
  tomcat:
    uri-encoding: UTF-8
#    basedir: /data/risinger/tomcat
    max-threads: 2000
    min-spare-threads: 10
    accesslog:
      pattern: common
      enabled: true
      directory: ../logs
      prefix: risinger-app
      suffix: .log
      request-attributes-enabled: true
      rename-on-rotate: true
logging:
  level:
    root: DEBUG
    com.bbd: DEBUG
    org.apache.shiro.cache.ehcache.EhCacheManager: WARN
    org.apache.shiro.session.mgt.AbstractValidatingSessionManager: WARN
spring:
  #数据库的配置
  datasource:
        name: test
        url: jdbc:mysql://192.168.174.128:3306/resinger_web_db?useUnicode=true&characterEncoding=utf-8
        username: root
        password: Zzp123456$
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 'x' FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
  #redis配置
  redis: 
     database: 0
     host: 192.168.174.128
     port: 6379
     password: 123456
     timeout: 0
     pool: 
       maxIdle: 300
       maxTotal: 60000
       testOnBorrow: true